### ISSUE TITLE
Consider deprecating in favour of redux-immutable

### ISSUE THREAD

**Issue by gajus** [indexiatech/redux-immutablejs#27]
Original thread: https://github.com/gajus/redux-immutable/issues/12#issuecomment-176189454

> @gaearon now that this update is out, can I ask you to replace `redux-immutablejs` with `redux-immutable` in http://redux.js.org/docs/introduction/Ecosystem.html#utilities?
> 
> The current implementation of `redux-immutable` is less opinionated (ironically, given the 1.0.0 version) and 2x faster (as asserted using [this primitive benchmark](https://github.com/gajus/redux-immutable/blob/5a5af3155073a4883f8cfc39a284e7f38d355dc8/benchmarks/> index.js)) than `redux-immutablejs`:
> 
> ```
> starting redux-immutablejs rootReducer iteration
> target rootReducer iteration x 338,215 ops/sec ±1.68% (84 runs sampled)
> ```
> 
> ```
> starting redux-immutable rootReducer iteration
> target rootReducer iteration x 721,491 ops/sec ±1.21% (89 runs sampled)
> ```
> 
> I will drop a message to @indexiatech suggesting:
> 
> * to deprecate `redux-immutablejs` in favour of `redux-immutable`
> * suggest to release [`createReducer`](https://github.com/indexiatech/redux-immutablejs#immutable-handler-map-reducer-creator) as a separate utility (which is the same route I am taking the Canonical Composition Pattern implementation)

Context:

I have recently released [`redux-immutable@2`](https://github.com/gajus/redux-immutable/tree/v2.0.2) that does no more and no less than allow state and `initialState` to be an instance of `Immutable.Iterable`.

I am moving all the Canonical Composition Pattern implementation under a different name that in turn will rely on `redux-immutable`. @asaf I'd like to suggest to do the same for [`createReducer`](https://github.com/indexiatech/redux-immutablejs#immutable-handler-map-reducer-creator).

I am happy to listen to your feedback should you have suggestions for `redux-immutable` improvement prior to deprecating `redux-immutablejs`.

**Comment by gaearon** [comment]
Please PR changes to Ecosystem.md?

**Comment by asaf** [comment]
@gaearon please review this issue, if this makes sense technically to you then I'll put the deprecation message.

Thanks!

**Comment by gaearon** [comment]
Since projects aren't completely equivalent I don't think deprecating it really makes sense unless you decide to split `createReducer()`. Even if you do, whether to deprecate it is completely up to you. 

I have no qualms about there being two competing solutions at all. Competition is great! We will recommend the more performant one officially because people using Immutable usually do so for perf. Ideally I'd love to see collaboration between projects, further improvements to performance [and bundle size](https://github.com/gajus/redux-immutable/issues/14), etc, so it would be nice if you folks could figure this out between yourselves.

I'm sorry if me merging a PR replacing your library with another came across as sneaky or passive aggressive!

**Comment by asaf** [comment]
@gaearon ack,
And sure!, not a problem, at the end, we all do the best for the community, aren't we? :-)

Closing,
Asaf.
